FROM rhscl/nodejs-4-rhel7

MAINTAINER OpenShift Development <dev@lists.openshift.redhat.com>

ENV APP_DIR=/opt/openshift-auth-proxy

COPY . ${APP_DIR}

USER 0 

RUN cd ${APP_DIR} && \
    scl enable rh-nodejs4 'npm install'

WORKDIR ${APP_DIR}

ENTRYPOINT ["./run.sh"]
